---
  # default jezziki-server config
  title: "jezziki.de"
  debug: true
  port: "8080"
  host: ""
  ssl: false
  paths:
    cert: "../static/dist/certs/lhcrt.pem"
    key: "../static/dist/certs/lhkey.pem"
    static: "../static/src"
    public: "../static/public"
    dash: "5fzt78g4A7fnb882"
    dist: "../static/dist"
  services:
    node_01: 8080
    node_02: 8081
    node_03: 8082
    node_04: 8083
    node_05: 8084
  rewrites:
      "/src/app/img/*": "/img/$1"
  links:
    favicon: "favicon.ico"
    stylesheets:
      - "https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      - "../src/app/app.css"
      - "../src/index.css"
  utils:
  components:
    - header
    - aside
    - article
    - nav
    - main
    - footer

